helper:
  myriad:
    environment:
      MYRIAD_TRANSPORT: redis
      MYRIAD_LOG_LEVEL: info
      MYRIAD_LIBRARY_PATH: /opt/app/lib
  fastapi:
    environment:
      LOG_LEVEL: info
setting:
  redis:
    which:
      - service/support/redis/single
service_config:
  custom:
    restart: always
