instance:
  0:
  1:
  2:
  3:
  4:
  5:

service_config:
  environment:
    REDIS_CLUSTER_DNS_LOOKUP_RETRIES: 30
    REDIS_CLUSTER_REPLICAS: 0
    REDIS_DNS_RETRIES: 30
    REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP: 10
    ALLOW_EMPTY_PASSWORD: yes
  docker_deployment:
    image: docker.io/bitnami/redis-cluster:6.2-debian-10


setting:
  helper_dependency:
    support_helper:
      - redis

