service_config:
  environment:
    REDIS_DNS_RETRIES: 30
    ALLOW_EMPTY_PASSWORD: yes
  docker_deployment:
    image: docker.io/bitnami/redis:6.2-debian-10


setting:
  helper_dependency:
    support_helper:
      - redis

